#!/usr/bin/env bash

E_OPTERROR=85

if [ $# -lt 1 ]    # Script invoked with no command-line args?
then
  echo "this script updates a hub in hwbtrax on epsilon"
  echo "Usage: `basename $0` hubName"
  exit $E_OPTERROR    # Exit and explain usage.
    # Usage: scriptname -options
    # Note: dash (-) necessary
fi


ssh bass@epsilon.bio.fsu.edu "public_html/hwbtrax/hub_update.sh $1"
